name: ci

# CI workflow: run on PRs and merges/pushes to main/master
on:
  pull_request:
    branches: [ "main", "master" ]
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: test-build

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python (PlatformIO Core is written in Python)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      #  Cache PlatformIO packages and libraries to speed up future builds
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cache/pip
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      # Install PlatformIO Core
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      # Install libraries/dependencies defined in platformio.ini
      - name: Install Library Dependencies
        run: pio pkg install


      # Set CI build metadata
      - name: Set Firmware Name
        run: |
          BUILD_ID="ci-${GITHUB_REF_NAME}-$(date +%Y%m%d)-${GITHUB_SHA::7}"
          echo "VERSION=${BUILD_ID}" >> $GITHUB_ENV

      # Compile the firmware with VERSION override
      - name: Build Firmware
        run: |
          export PLATFORMIO_BUILD_FLAGS="-D VERSION=\"$VERSION\""
          pio run -e esp32doit-devkit-v1

      # Rename the output firmware file 
      - name: Rename Firmware
        run: |
          mv .pio/build/esp32doit-devkit-v1/firmware.bin firmware-$VERSION.bin

      # Upload the compiled firmware as an artifact
      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ env.VERSION }}.bin
          path: firmware-${{ env.VERSION }}.bin

